version: 2.1

orbs:
  win: circleci/windows@1.0.0

jobs:
  build:
    executor:
      name: win/vs2019
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore MyBudget.sln
      - run:
          name: "Run Build step"
          command: dotnet.exe build MyBudget.sln
      - store_artifacts:
          path: .\bin\